# Generated by Django 3.1.7 on 2023-03-15 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roles',
            options={'ordering': ['role'], 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='rolesusers',
            options={'ordering': ['role'], 'verbose_name_plural': 'Roles users'},
        ),
    ]
