# Generated by Django 3.1.7 on 2021-06-17 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.CharField(blank=True, max_length=255, null=True)),
                ('cmgdem_file', models.FileField(blank=True, null=True, upload_to='storage/sddp/dbs')),
                ('genpltproy_file', models.FileField(blank=True, help_text=' En caso de que sea la base de datos del proyecto, los archivos de generacion o preferiblemente el genpltproy.csv generado por el script que toma los datos de la planta del proyecto, esto agiliza este procedimiento de forma drastica.', null=True, upload_to='storage/sddp/dbs')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('value', models.FloatField()),
                ('resolution', models.CharField(max_length=255)),
                ('tension_level', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WeightBlocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.IntegerField()),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('demand_factor', models.FloatField(null=True)),
                ('trm', models.IntegerField(null=True)),
                ('trm_date', models.DateField()),
                ('start_date', models.DateField()),
                ('limit_date', models.DateField()),
                ('file', models.FileField(blank=True, null=True, upload_to='storage/sddp/projects')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='MarginalCostDemand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.IntegerField()),
                ('serie', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('db', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sddp.db')),
            ],
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.IntegerField()),
                ('serie', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('db', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sddp.db')),
            ],
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.IntegerField()),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('project', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sddp.project')),
            ],
        ),
        migrations.AddField(
            model_name='db',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='dbs', to='sddp.project'),
        ),
    ]
