# Generated by Django 3.1.7 on 2021-11-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reported_hours', '0005_reportedhours'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoreport',
            name='email',
            field=models.BooleanField(default=False),
        ),
    ]
