# Generated by Django 3.1.7 on 2021-12-15 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_max', models.IntegerField(blank=True, null=True)),
                ('notify_days_max', models.IntegerField(blank=True, null=True)),
                ('group_notify_days_max', models.CharField(blank=True, max_length=500, null=True)),
                ('group_notify_request', models.CharField(blank=True, max_length=500, null=True)),
                ('notify_request_pending', models.IntegerField(blank=True, null=True)),
                ('group_notify_request_pending', models.CharField(blank=True, max_length=500, null=True)),
                ('group_notify_request_accepted', models.CharField(blank=True, max_length=500, null=True)),
                ('group_notify_request_deny_final_acceptor', models.CharField(blank=True, max_length=500, null=True)),
                ('group_notify_liquidation_deny', models.CharField(blank=True, max_length=500, null=True)),
                ('final_acceptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
