# Generated by Django 3.1.7 on 2021-12-15 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacations', '0002_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_leader', models.BooleanField(default=None, null=True)),
                ('date_leader', models.DateTimeField()),
                ('accepted_final_acceptor', models.BooleanField(default=None, null=True)),
                ('date_final_acceptor', models.DateTimeField()),
                ('request_completed', models.BooleanField(default=False)),
                ('start_date_vacations', models.DateTimeField()),
                ('end_date_vacations', models.DateTimeField()),
                ('calendar_days_taken', models.IntegerField()),
                ('business_days_taken', models.IntegerField()),
                ('accepted_liquidation', models.BooleanField(default=None, null=True)),
                ('path_liquidation', models.CharField(max_length=255)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacations.collaborator')),
                ('final_acceptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_acceptor', to=settings.AUTH_USER_MODEL)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
