# Generated by Django 3.1.7 on 2021-12-16 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacations', '0003_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='accepted_final_acceptor',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='accepted_leader',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='accepted_liquidation',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='business_days_taken',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='calendar_days_taken',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='date_final_acceptor',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='date_leader',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='end_date_vacations',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='final_acceptor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_acceptor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requests',
            name='path_liquidation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='request_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='start_date_vacations',
            field=models.DateField(blank=True, null=True),
        ),
    ]
