# Generated by Django 3.1.7 on 2021-12-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0005_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='id_card',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
