# Generated by Django 3.1.7 on 2021-12-21 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0005_bonus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonus',
            options={'ordering': ['-id'], 'verbose_name': 'Bonus'},
        ),
        migrations.AlterModelOptions(
            name='collaborator',
            options={'ordering': ['entry_at'], 'verbose_name': 'Collaborators'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'ordering': ['id'], 'verbose_name': 'Settings'},
        ),
    ]
