# Generated by Django 3.1.7 on 2021-12-21 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0006_auto_20211221_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requests',
            options={'ordering': ['-id'], 'verbose_name': 'Requests'},
        ),
    ]
