# Generated by Django 3.1.7 on 2021-12-22 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0007_auto_20211221_1430'),
        ('vacations', '0006_collaborator_id_card'),
    ]

    operations = [
    ]
