# Generated by Django 3.1.7 on 2021-12-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0009_collaborator_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
