# Generated by Django 3.1.7 on 2021-12-29 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0011_auto_20211228_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaysCaused',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_days', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacations.collaborator')),
            ],
            options={
                'verbose_name': 'Days Caused',
                'ordering': ['-id'],
            },
        ),
    ]
