# Generated by Django 3.1.7 on 2021-12-29 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0012_dayscaused'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dayscaused',
            old_name='extra_days',
            new_name='days_caused',
        ),
    ]
