# Generated by Django 3.1.7 on 2021-12-29 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0013_auto_20211228_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='avalaible_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='days_taken',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
