# Generated by Django 3.1.7 on 2022-01-05 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0016_auto_20220105_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborator',
            name='avalaible_days',
        ),
        migrations.RemoveField(
            model_name='collaborator',
            name='days_taken',
        ),
    ]
