# Generated by Django 3.1.7 on 2022-01-11 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0017_auto_20220105_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='salary',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='group_notify_days_max',
            field=models.CharField(blank=True, default='[]', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='group_notify_liquidation_deny',
            field=models.CharField(blank=True, default='[]', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='group_notify_request',
            field=models.CharField(blank=True, default='[]', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='group_notify_request_accepted',
            field=models.CharField(blank=True, default='[]', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='group_notify_request_deny_final_acceptor',
            field=models.CharField(blank=True, default='[]', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='group_notify_request_pending',
            field=models.CharField(blank=True, default='[]', max_length=500, null=True),
        ),
    ]
