# Generated by Django 3.1.7 on 2022-02-09 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0018_auto_20220110_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='state',
            field=models.IntegerField(choices=[(2, 'Inactivo'), (1, 'Activo')], default=1),
        ),
    ]
