# Generated by Django 3.1.7 on 2022-02-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0019_collaborator_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='state',
            field=models.IntegerField(choices=[(2, 'Retirado'), (1, 'Activo')], default=1),
        ),
    ]
