# Generated by Django 3.1.7 on 2022-04-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0020_auto_20220228_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='state',
            field=models.IntegerField(choices=[(1, 'Activo'), (2, 'Retirado')], default=1),
        ),
    ]
