# Generated by Django 3.1.7 on 2022-08-12 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0019_auto_20220610_1515'),
        ('vacations', '0022_requests_comments'),
    ]

    operations = [
    ]
