# Generated by Django 3.1.7 on 2023-03-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0023_merge_20220812_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='state',
            field=models.IntegerField(choices=[(2, 'Retirado'), (1, 'Activo')], default=1),
        ),
    ]
