# Generated by Django 3.1.7 on 2021-06-23 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlsFilesMetricTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seconds', models.IntegerField()),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imports.metric')),
            ],
        ),
    ]
