# Generated by Django 3.1.7 on 2021-07-01 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0005_auto_20210623_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='neteffectivecapacity',
            name='fuel',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, to='imports.fuel'),
            preserve_default=False,
        ),
    ]
