# Generated by Django 3.1.7 on 2021-07-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0006_neteffectivecapacity_fuel'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='neteffectivecapacity',
            name='unique_NetEffectiveCapacity',
        ),
        migrations.AddConstraint(
            model_name='neteffectivecapacity',
            constraint=models.UniqueConstraint(fields=('date', 'resource', 'agent', 'fuel'), name='unique_NetEffectiveCapacity'),
        ),
    ]
