# Generated by Django 3.1.7 on 2021-08-27 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0007_auto_20210701_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservoir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyReserves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('useful_capacity_volume', models.FloatField(null=True)),
                ('maximum_technical_volume_energy', models.FloatField(null=True)),
                ('useful_capacity_energy', models.FloatField(null=True)),
                ('useful_daily_volume', models.FloatField(null=True)),
                ('daily_useful_volume_energy', models.FloatField(null=True)),
                ('useful_dailyvolume', models.FloatField(null=True)),
                ('hydrological_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imports.hydrologicalregion')),
                ('reservoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imports.reservoir')),
            ],
        ),
    ]
