# Generated by Django 3.1.7 on 2021-08-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0009_auto_20210828_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyreserves',
            name='date',
            field=models.DateField(),
        ),
    ]
