# Generated by Django 3.1.7 on 2021-11-08 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgeted_hours', '0004_auto_20211015_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='VisitRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_record', models.DateTimeField()),
                ('date_visit', models.DateTimeField()),
                ('phc_code', models.CharField(max_length=100)),
                ('customer_commitments', models.CharField(blank=True, max_length=100, null=True)),
                ('is_in_crm', models.BooleanField(default=False)),
                ('validated_in_crm', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgeted_hours.client')),
                ('interaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_business_interactions.interactiontype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
