# Generated by Django 3.1.7 on 2021-11-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_business_interactions', '0002_auto_20211110_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitrecord',
            name='validated_in_crm',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
