# Generated by Django 3.1.7 on 2021-11-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_business_interactions', '0005_auto_20211129_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitrecord',
            name='customer_commitments',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='visitrecord',
            name='phc_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
