# Generated by Django 3.1.7 on 2022-09-29 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['area'], 'verbose_name': 'Area'},
        ),
        migrations.AlterModelOptions(
            name='templates',
            options={'ordering': ['title'], 'verbose_name': 'Templates'},
        ),
        migrations.AddField(
            model_name='templates',
            name='created_at',
            field=models.DateField(default='2022-09-29'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='templates',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
