# Generated by Django 3.1.7 on 2022-06-10 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Fuel',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FuelPriceOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Fuel price option',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GrowingRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Growing rate',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlantType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('enficc_factor', models.FloatField(blank=True, default=0, null=True)),
                ('flexible', models.BooleanField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Plant type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('year_init_optimization', models.IntegerField(blank=True, default=0, null=True)),
                ('year_end_optimization', models.IntegerField(blank=True, default=0, null=True)),
                ('periodicity_auction', models.IntegerField(blank=True, default=0, null=True)),
                ('regasification_init', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.IntegerField(blank=True, default=0, null=True)),
                ('file', models.FileField(upload_to='storage/sddp/projects')),
                ('create_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fuel_price_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration_sddp.fuelpriceoption')),
                ('growing_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration_sddp.growingrate')),
            ],
            options={
                'verbose_name': 'Project',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MetaMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, default=0, null=True)),
                ('wind', models.FloatField(blank=True, default=0, null=True)),
                ('solar', models.FloatField(blank=True, default=0, null=True)),
                ('pch', models.FloatField(blank=True, default=0, null=True)),
                ('thermal_not_centralized', models.FloatField(blank=True, default=0, null=True)),
                ('renewable_not_conventional', models.FloatField(blank=True, default=0, null=True)),
                ('liquid', models.FloatField(blank=True, default=0, null=True)),
                ('coal', models.FloatField(blank=True, default=0, null=True)),
                ('gas', models.FloatField(blank=True, default=0, null=True)),
                ('glp', models.FloatField(blank=True, default=0, null=True)),
                ('hidro', models.FloatField(blank=True, default=0, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration_sddp.project')),
            ],
            options={
                'verbose_name': 'Meta matrix',
                'ordering': ['project'],
            },
        ),
        migrations.CreateModel(
            name='MaxNewCapacity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, default=0, null=True)),
                ('wind', models.FloatField(blank=True, default=0, null=True)),
                ('solar', models.FloatField(blank=True, default=0, null=True)),
                ('pch', models.FloatField(blank=True, default=0, null=True)),
                ('thermal_not_centralized', models.FloatField(blank=True, default=0, null=True)),
                ('renewable_not_conventional', models.FloatField(blank=True, default=0, null=True)),
                ('liquid', models.FloatField(blank=True, default=0, null=True)),
                ('coal', models.FloatField(blank=True, default=0, null=True)),
                ('gas', models.FloatField(blank=True, default=0, null=True)),
                ('glp', models.FloatField(blank=True, default=0, null=True)),
                ('hidro', models.FloatField(blank=True, default=0, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration_sddp.project')),
            ],
            options={
                'verbose_name': 'Max new capacity',
                'ordering': ['project'],
            },
        ),
        migrations.CreateModel(
            name='LcoeEnergyCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, default=0, null=True)),
                ('wind', models.FloatField(blank=True, default=0, null=True)),
                ('solar', models.FloatField(blank=True, default=0, null=True)),
                ('pch', models.FloatField(blank=True, default=0, null=True)),
                ('thermal_not_centralized', models.FloatField(blank=True, default=0, null=True)),
                ('renewable_not_conventional', models.FloatField(blank=True, default=0, null=True)),
                ('liquid', models.FloatField(blank=True, default=0, null=True)),
                ('coal', models.FloatField(blank=True, default=0, null=True)),
                ('gas', models.FloatField(blank=True, default=0, null=True)),
                ('glp', models.FloatField(blank=True, default=0, null=True)),
                ('hidro', models.FloatField(blank=True, default=0, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration_sddp.project')),
            ],
            options={
                'verbose_name': 'Lcoe energy cost',
                'ordering': ['project'],
            },
        ),
        migrations.CreateModel(
            name='GraphYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration_sddp.project')),
            ],
            options={
                'verbose_name': 'Graph year',
                'ordering': ['project'],
            },
        ),
        migrations.CreateModel(
            name='FuturePlants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('reliability_obligation', models.FloatField(blank=True, default=0, null=True)),
                ('long_term_contract', models.FloatField(blank=True, default=0, null=True)),
                ('central_dispatch', models.BooleanField(blank=True, default=None, null=True)),
                ('nominal_power', models.FloatField(blank=True, default=0, null=True)),
                ('start_at', models.DateField(blank=True, null=True)),
                ('fuel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration_sddp.fuel')),
                ('plant_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration_sddp.planttype')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration_sddp.project')),
            ],
            options={
                'verbose_name': 'Future plants',
                'ordering': ['project'],
            },
        ),
        migrations.CreateModel(
            name='ExistingPlants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('reliability_obligation', models.FloatField(blank=True, default=0, null=True)),
                ('long_term_contract', models.FloatField(blank=True, default=0, null=True)),
                ('central_dispatch', models.BooleanField(blank=True, default=None, null=True)),
                ('nominal_power', models.FloatField(blank=True, default=0, null=True)),
                ('fuel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration_sddp.fuel')),
                ('plant_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration_sddp.planttype')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration_sddp.project')),
            ],
            options={
                'verbose_name': 'Existing plants',
                'ordering': ['project'],
            },
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand_at', models.DateField()),
                ('month_days', models.IntegerField()),
                ('value', models.FloatField(blank=True, default=0, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration_sddp.project')),
            ],
            options={
                'verbose_name': 'Demand',
                'ordering': ['project'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalCapacity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, default=0, null=True)),
                ('wind', models.FloatField(blank=True, default=0, null=True)),
                ('solar', models.FloatField(blank=True, default=0, null=True)),
                ('pch', models.FloatField(blank=True, default=0, null=True)),
                ('thermal_not_centralized', models.FloatField(blank=True, default=0, null=True)),
                ('renewable_not_conventional', models.FloatField(blank=True, default=0, null=True)),
                ('liquid', models.FloatField(blank=True, default=0, null=True)),
                ('coal', models.FloatField(blank=True, default=0, null=True)),
                ('gas', models.FloatField(blank=True, default=0, null=True)),
                ('glp', models.FloatField(blank=True, default=0, null=True)),
                ('hidro', models.FloatField(blank=True, default=0, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration_sddp.project')),
            ],
            options={
                'verbose_name': 'Additional capacity',
                'ordering': ['project'],
            },
        ),
    ]
