# Generated by Django 3.1.7 on 2022-10-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration_sddp', '0004_auto_20220721_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalcapacity',
            name='renewable_not_conventional',
        ),
        migrations.RemoveField(
            model_name='lcoeenergycost',
            name='renewable_not_conventional',
        ),
        migrations.RemoveField(
            model_name='maxnewcapacity',
            name='renewable_not_conventional',
        ),
        migrations.RemoveField(
            model_name='metamatrix',
            name='renewable_not_conventional',
        ),
        migrations.AddField(
            model_name='additionalcapacity',
            name='iteration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='additionalcapacity',
            name='relaxation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
