# Generated by Django 3.1.7 on 2023-03-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_team', models.CharField(max_length=50)),
                ('visiting_team', models.CharField(max_length=50)),
                ('local_goals', models.IntegerField(default=0)),
                ('away_goals', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Team',
                'ordering': ['name'],
            },
        ),
    ]
