# Generated by Django 3.1.7 on 2021-09-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeted_hours', '0002_budgetedhourshistorydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetedhours',
            name='state',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Aprobado'), (3, 'No aprobado')], default=1),
        ),
    ]
