# Generated by Django 3.1.7 on 2021-10-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeted_hours', '0003_budgetedhours_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='description',
            field=models.TextField(blank=True, max_length=700, null=True),
        ),
    ]
