# Generated by Django 3.1.7 on 2021-10-21 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgeted_hours', '0004_auto_20211015_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetedHoursCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(blank=True, default=0, null=True)),
                ('BudgetedHours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgeted_hours.budgetedhours')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgeted_hours.categories')),
            ],
            options={
                'verbose_name': 'Budgeted hours categories',
                'ordering': ['id'],
            },
        ),
    ]
