# Generated by Django 3.1.7 on 2021-10-21 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgeted_hours', '0005_budgetedhourscategories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budgetedhourscategories',
            old_name='BudgetedHours',
            new_name='budgeted_hours',
        ),
    ]
