# Generated by Django 3.1.7 on 2021-10-21 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgeted_hours', '0006_auto_20211021_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hours',
            name='version',
        ),
        migrations.CreateModel(
            name='Versions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('budgeted_hours_categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgeted_hours.budgetedhourscategories')),
            ],
            options={
                'verbose_name': 'Versions',
                'ordering': ['id'],
            },
        ),
    ]
