# Generated by Django 3.1.7 on 2021-10-21 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgeted_hours', '0008_hours_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='versions',
            options={'ordering': ['version'], 'verbose_name': 'Versions'},
        ),
    ]
