# Generated by Django 3.1.7 on 2021-10-21 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgeted_hours', '0009_auto_20211021_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='versions',
            options={'ordering': ['budgeted_hours_categories'], 'verbose_name': 'Versions'},
        ),
    ]
