# Generated by Django 3.1.7 on 2021-11-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeted_hours', '0011_auto_20211026_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetedhours',
            name='description',
            field=models.TextField(blank=True, max_length=700, null=True),
        ),
    ]
