# Generated by Django 3.1.7 on 2021-12-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeted_hours', '0012_budgetedhours_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetedHoursFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(blank=True, max_length=255, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('files', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
