# Generated by Django 3.1.7 on 2021-12-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeted_hours', '0013_budgetedhoursfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='hours',
            name='senior_leader',
            field=models.FloatField(default=0),
        ),
    ]
