# Generated by Django 3.1.7 on 2021-12-13 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgeted_hours', '0014_hours_senior_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetedhoursfiles',
            name='budgeted_hours',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='budgeted_hours.budgetedhours'),
            preserve_default=False,
        ),
    ]
