# Generated by Django 3.1.7 on 2022-01-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeted_hours', '0015_budgetedhoursfiles_budgeted_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetedhours',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
