# Generated by Django 3.1.7 on 2022-02-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeted_hours', '0016_budgetedhours_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetedhours',
            name='stages',
            field=models.IntegerField(choices=[(1, 'En revisión comercial'), (2, 'En revisión técnica'), (3, 'En revisión financiero'), (4, 'Finalizado')], default=1),
        ),
        migrations.AlterField(
            model_name='budgetedhours',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
