# Generated by Django 3.1.7 on 2022-02-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeted_hours', '0018_traceabilitybudgetedhourshistory_stages'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetedhours',
            name='document_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='budgetedhours',
            name='duration_deliverables',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='budgetedhours',
            name='start_project_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
