# Generated by Django 3.1.7 on 2022-03-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeted_hours', '0021_auto_20220225_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetedhours',
            name='start_at',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
    ]
