# Generated by Django 3.1.7 on 2022-04-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeted_hours', '0023_auto_20220311_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetedhours',
            name='contract_signed',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='budgetedhours',
            name='document_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='budgetedhours',
            name='duration_deliverables',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='budgetedhours',
            name='project_depends',
            field=models.IntegerField(blank=True, choices=[(1, 'Contrato'), (2, 'Reunión de Inicio'), (3, 'Otro')], null=True),
        ),
        migrations.AddField(
            model_name='budgetedhours',
            name='project_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Proyecto corta duración'), (2, 'Proyecto media duración'), (3, 'Proyecto larga duración')], null=True),
        ),
        migrations.AddField(
            model_name='budgetedhours',
            name='start_at',
            field=models.DateField(default='2022-04-01'),
            preserve_default=False,
        ),
    ]
