# Generated by Django 3.1.7 on 2022-08-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeted_hours', '0024_auto_20220401_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetedhours',
            name='compromise_delivery_at',
            field=models.DateField(default='2022-01-01'),
            preserve_default=False,
        ),
    ]
