# Generated by Django 3.1.7 on 2022-08-29 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgeted_hours', '0024_auto_20220401_1218'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Zones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProtectionCoordinationStudies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('lesson_type', models.IntegerField(choices=[(1, 'Técnica'), (2, 'Gestión del proyecto'), (3, 'General')])),
                ('description', models.TextField(blank=True, null=True)),
                ('subcategory', models.IntegerField(blank=True, choices=[(1, 'Función de protección'), (2, 'Simulación'), (3, 'Informe'), (4, 'Otro')], null=True)),
                ('subcategory_description', models.TextField(blank=True, null=True)),
                ('element_type', models.IntegerField(blank=True, choices=[(1, 'Generador fotovoltaico'), (2, 'Generador hidráulico'), (3, 'Subestación de transmisión'), (4, 'Subestación de distribución'), (5, 'Generador térmico'), (6, 'Generador eólico'), (7, 'Transformador'), (8, 'Barra'), (9, 'Línea'), (10, 'Otro')], null=True)),
                ('element_type_description', models.TextField(blank=True, null=True)),
                ('protection', models.CharField(blank=True, max_length=255, null=True)),
                ('relay_brand', models.IntegerField(blank=True, choices=[(1, 'Siemens'), (2, 'GE'), (3, 'ABB'), (4, 'SEL'), (5, 'Schneider'), (6, 'ZIV'), (7, 'Fusible'), (8, 'CB'), (9, 'General'), (10, 'Otro')], null=True)),
                ('relay_brand_description', models.TextField(blank=True, null=True)),
                ('relay_model', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='static/static/lessons/protection_coordination_studies')),
                ('budgeted_hours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgeted_hours.budgetedhours')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgeted_hours.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Protection coordination studies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Operators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.zones')),
            ],
            options={
                'verbose_name': 'Operator',
                'verbose_name_plural': 'Operators',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MarketStudies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('study_type', models.IntegerField(blank=True, choices=[(1, 'Estudio de mercado'), (2, 'Proyección de precios'), (3, 'Estudios energéticos - Estudios de conexión'), (4, 'Asesoría')], null=True)),
                ('lesson_type', models.IntegerField(choices=[(1, 'Técnica'), (2, 'Gestión del proyecto'), (3, 'General')])),
                ('subcategory', models.IntegerField(blank=True, choices=[(1, 'Ajuste de la base de datos'), (2, 'Revisión de la información'), (3, 'Análisis'), (4, 'Informe y anexos')], null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='static/static/lessons/market_studies')),
                ('budgeted_hours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgeted_hours.budgetedhours')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgeted_hours.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Market studies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ElectricalStudies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('lesson_type', models.IntegerField(choices=[(1, 'Técnica'), (2, 'Gestión del proyecto'), (3, 'General')])),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='static/static/lessons/electrical_studies')),
                ('budgeted_hours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgeted_hours.budgetedhours')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgeted_hours.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Electrical studies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Consultancies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('lesson_type', models.IntegerField(choices=[(1, 'Técnica'), (2, 'Gestión del proyecto'), (3, 'General')])),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='static/static/lessons/consultancies')),
                ('budgeted_hours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgeted_hours.budgetedhours')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgeted_hours.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consultancies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConnectionStudies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('lesson_type', models.IntegerField(choices=[(1, 'Técnica'), (2, 'Gestión del proyecto'), (3, 'General')])),
                ('subcategory', models.IntegerField(blank=True, choices=[(1, 'Ajuste de la base de datos'), (2, 'Revisión de la información'), (3, 'Análisis'), (4, 'Informe y anexos')], null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='static/static/lessons/connection_studies')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.areas')),
                ('budgeted_hours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgeted_hours.budgetedhours')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgeted_hours.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.operators')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.zones')),
            ],
            options={
                'verbose_name': 'Connection studies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='areas',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.operators'),
        ),
    ]
