# Generated by Django 3.1.7 on 2022-09-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protectioncoordinationstudies',
            name='element_type_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='protectioncoordinationstudies',
            name='relay_brand_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='protectioncoordinationstudies',
            name='subcategory_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
