# Generated by Django 3.1.7 on 2022-09-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_auto_20220902_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionstudies',
            name='action_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultancies',
            name='action_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electricalstudies',
            name='action_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketstudies',
            name='action_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protectioncoordinationstudies',
            name='action_plan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
